import {
  BEHAVIOR_WEIGHTS, PS_KNOWLEDGE_WEIGHTS, validateCase,
  type Behavior, type CourseCase, type Knowledge, type Phase,
} from '../lib/emailCourse'

// Authored simulation fixtures for the demo company, not imported production email.
// Each campaign is a distinct scenario. A phase has two candidates per objective:
// one may be selected initially and the other reserved for an unseen reassessment.
interface Scenario {
  id: string; phase: Phase; objective: Knowledge; decision: 'legitimate' | 'phishing';
  from: string; subject: string; body: string; context: string;
  behavior?: Partial<Record<Behavior, number>>; primary?: Behavior;
  indicators?: Partial<Record<keyof typeof PS_KNOWLEDGE_WEIGHTS, number>>;
  records: [string, string, Knowledge][]; explanation: string;
}
function authored(s: Scenario): CourseCase {
  const c: CourseCase = {
    id: `starter-${s.id}-v1`, campaignId: `starter-${s.id}`, phase: s.phase,
    objective: s.objective, challenge: `${s.phase}-${s.objective}-v1`,
    public: {
      from: s.from, to: 'learner@sentri.example', subject: s.subject, body: s.body, context: s.context,
      evidence: [
        ...s.records.map(([label, detail], i) => ({ id: `record-${i + 1}`, label, detail })),
        { id: 'format', label: 'Message formatting', detail: 'The message uses a standard email layout and has no spelling errors.' },
      ],
    },
    // Zero explicitly means the cue was assessed and is absent, not missing data.
    behavior: { ...Object.fromEntries(Object.keys(BEHAVIOR_WEIGHTS).map(k => [k, 0])), ...s.behavior } as CourseCase['behavior'],
    indicators: { ...Object.fromEntries(Object.keys(PS_KNOWLEDGE_WEIGHTS).map(k => [k, 0])), ...s.indicators } as CourseCase['indicators'],
    primaryBehavior: s.primary ?? null,
    rubric: {
      decision: s.decision,
      evidenceAlternatives: [s.records.map((_, i) => `record-${i + 1}`)],
      criticalEvidence: ['record-1'],
      knowledgeChecks: [
        ...s.records.map(([, , tag], i) => ({ tag, evidenceId: `record-${i + 1}`, expectedSelected: true })),
        ...[...new Set(s.records.map(r => r[2]))].map(tag => ({ tag, evidenceId: 'format', expectedSelected: false })),
      ],
      explanation: s.explanation,
      hints: ['Compare the message with the independent records. Formatting alone does not establish trust.', 'Select the records that explain your decision, including the requested action.'],
    },
  }
  validateCase(c)
  return c
}

export const STARTER_CATALOG: CourseCase[] = [
  authored({ id: 'bonus-team', phase: 'easy', objective: 'senderIdentity', decision: 'phishing',
    from: 'Rewards Team <benefits@sentri-bonus.example>', subject: 'Your employee bonus is ready',
    body: 'Your department has been selected for an extra bonus. Reply with your employee portal password so we can activate your award.',
    context: 'The company directory lists benefits@sentri.example for benefit questions.',
    behavior: { rewardIncentive: 1, familiarityImpersonation: .5 }, primary: 'rewardIncentive',
    indicators: { senderIdentity: 1, credentialProtection: 1, requestContext: .75 },
    records: [['Sender record', 'The full sender address is benefits@sentri-bonus.example. The directory address is benefits@sentri.example.', 'senderIdentity'], ['Requested information', 'The message asks for your portal password in an email reply. The benefits team does not need that password to process awards.', 'credentialProtection']],
    explanation: 'The sender differs from the independently listed benefits address, and the request would expose your password. Report the message through the company reporting channel.',
  }),
  authored({ id: 'room-booking', phase: 'easy', objective: 'senderIdentity', decision: 'legitimate',
    from: 'Facilities <facilities@sentri.example>', subject: 'Meeting room booking confirmed',
    body: 'Your booking for Cedar Room at 14:00 tomorrow is confirmed. You can review the reservation in the usual booking app. No reply is needed.',
    context: 'You booked Cedar Room ten minutes ago using the company booking app.',
    records: [['Booking app record', 'The independently opened booking app shows this confirmation from facilities@sentri.example for your reservation.', 'senderIdentity'], ['Reservation details', 'Room, time and booking reference match the reservation you made. The message requests no data or additional access.', 'requestContext']],
    explanation: 'The confirmation is corroborated inside the independently opened booking app and matches your requested booking. This is a legitimate message in this scenario.',
  }),
  authored({ id: 'storage-lock', phase: 'easy', objective: 'linkDestination', decision: 'phishing',
    from: 'Storage Admin <service@storage-alert.example>', subject: 'Your files will be locked today',
    body: 'Your storage access expires in one hour. Restore access now: https://sentri.example.storage-alert.example/sign-in',
    context: 'Company storage is accessed through storage.sentri.example. No access change is scheduled.',
    behavior: { urgency: 1, fear: .75, authority: .5 }, primary: 'urgency',
    indicators: { linkDestination: 1, credentialProtection: .75, requestContext: .5 },
    records: [['Destination record', 'The destination host is sentri.example.storage-alert.example. Its base domain is storage-alert.example, not the company domain sentri.example.', 'linkDestination'], ['Service status', 'The independently opened company storage app shows active access with no pending expiry.', 'requestContext']],
    explanation: 'The destination belongs to a different domain and the claimed access expiry conflicts with the storage app. The HTTPS prefix does not establish that the destination is the company portal.',
  }),
  authored({ id: 'canteen-menu', phase: 'easy', objective: 'linkDestination', decision: 'legitimate',
    from: 'Facilities <facilities@sentri.example>', subject: 'Next week’s canteen menu',
    body: 'The new menu is available at https://intranet.sentri.example/canteen. You can also open Canteen from your usual intranet bookmark.',
    context: 'Facilities publishes a weekly menu on the company intranet.',
    records: [['Destination record', 'The displayed and actual destination both match https://intranet.sentri.example/canteen, the menu page in the company bookmark list.', 'linkDestination'], ['Independent intranet record', 'The independently opened intranet contains the same menu announcement. It requests no credentials outside the usual company sign-in.', 'requestContext']],
    explanation: 'Both the destination and announcement are corroborated through the known intranet. Use the usual bookmark to view the menu.',
  }),
  authored({ id: 'resume-viewer', phase: 'normal', objective: 'attachmentSafety', decision: 'phishing',
    from: 'Applicant <candidate@portfolio-mail.example>', subject: 'Portfolio for the open role',
    body: 'My portfolio is attached. Please run Portfolio.pdf.exe to view it; the viewer is needed for the interactive pages.',
    context: 'Your team accepts PDF portfolios through the recruitment portal. Applications do not require installing a viewer supplied by an applicant.',
    behavior: { curiosity: .75, helpfulness: .5 }, primary: 'curiosity',
    indicators: { attachmentSafety: 1, requestContext: .75, authorizationChecks: .5 },
    records: [['Attachment properties', 'The full filename is Portfolio.pdf.exe. The attachment is a Windows executable, not a PDF document.', 'attachmentSafety'], ['Recruitment workflow', 'The approved workflow accepts documents through the recruitment portal and does not require executing applicant software.', 'requestContext']],
    explanation: 'The disguised executable and request to run applicant-supplied software conflict with the recruitment workflow. Do not run it; report it for review.',
  }),
  authored({ id: 'audit-agenda', phase: 'normal', objective: 'attachmentSafety', decision: 'legitimate',
    from: 'Audit Coordinator <audit@sentri.example>', subject: 'Requested audit agenda',
    body: 'Attached is the agenda you requested in ticket AUD-28. The same PDF is available in the approved audit workspace.',
    context: 'You requested this agenda in the audit workspace yesterday. The workspace and email reference the same ticket.',
    records: [['Attachment and workspace comparison', 'Agenda.pdf is a PDF with no embedded executable or script. It matches the document retrieved from the independently opened approved audit workspace.', 'attachmentSafety'], ['Request record', 'Ticket AUD-28 records your request for this agenda and names audit@sentri.example as the coordinator.', 'requestContext']],
    explanation: 'The file matches the expected document in the independently opened workspace and your request record. The PDF extension alone would not have established safety.',
  }),
  authored({ id: 'colleague-remote-help', phase: 'normal', objective: 'requestContext', decision: 'phishing',
    from: 'Colleague Support <team-help@external-assist.example>', subject: 'Can you help a colleague finish their shift?',
    body: 'A colleague is locked out. Install our remote assistance tool and send its connection code so we can use your signed-in computer to finish their work.',
    context: 'Company help desk sessions require a verified internal ticket and the approved remote support client.',
    behavior: { helpfulness: 1, familiarityImpersonation: .5 }, primary: 'helpfulness',
    indicators: { requestContext: 1, authorizationChecks: 1, senderIdentity: .5 },
    records: [['Support ticket record', 'No internal ticket exists for this request. The message proposes using your signed-in session to do another person’s work.', 'requestContext'], ['Requested access', 'The supplied tool would let an external party control your workstation; the requester is not listed in the approved support directory.', 'authorizationChecks']],
    explanation: 'The request bypasses the verified support process and would give an unverified party control of your session. Contact help desk through the internal directory.',
  }),
  authored({ id: 'fire-drill-update', phase: 'normal', objective: 'requestContext', decision: 'legitimate',
    from: 'Site Safety <safety@sentri.example>', subject: 'Today’s drill moved to 15:00',
    body: 'Please tell your team that today’s evacuation drill starts at 15:00 instead of 14:00. No other action is needed.',
    context: 'A drill is scheduled today. Time-sensitive operational messages are sometimes legitimate.',
    records: [['Safety schedule', 'The independently opened site safety board confirms the revised 15:00 drill and the same announcement.', 'requestContext'], ['Requested action', 'The message asks you to communicate a confirmed schedule change. It requests no sensitive records, credentials, payment or access change.', 'authorizationChecks']],
    explanation: 'The time-sensitive update is corroborated through the safety board and requests a routine action. Urgency by itself does not make an email phishing.',
  }),
  authored({ id: 'support-otp', phase: 'hard', objective: 'credentialProtection', decision: 'phishing',
    from: 'IT Help Desk <helpdesk@sentri.example>', subject: 'Re: Your laptop support ticket',
    body: 'To finish your existing ticket, reply with the six-digit sign-in code from your authenticator. We can complete the repair faster with that code.',
    context: 'You have a real laptop ticket. A matching sender and ticket reference do not authorize a request for authentication secrets.',
    behavior: { authority: .75, familiarityImpersonation: .75 }, primary: 'authority',
    indicators: { credentialProtection: 1, mfaSafety: 1, requestContext: .75 },
    records: [['Authentication request', 'The code requested is a sign-in factor for your account. The company support policy prohibits sharing sign-in codes with support personnel.', 'credentialProtection'], ['Ticket portal record', 'The independently opened ticket portal has no request for an authentication code and states repairs can proceed without one.', 'mfaSafety']],
    explanation: 'Even a message in a real support thread must not be given your sign-in code. The secret request and conflicting ticket record identify this as a phishing attempt in the scenario.',
  }),
  authored({ id: 'recovery-key-upload', phase: 'hard', objective: 'credentialProtection', decision: 'phishing',
    from: 'Migration Coordinator <migration@sentri.example>', subject: 'Account continuity during the migration',
    body: 'Please paste your account recovery codes into the shared migration spreadsheet. This will help us restore your access if the migration fails.',
    context: 'A genuine migration is planned. Its approved instructions say users keep their recovery codes private.',
    behavior: { fear: .75, helpfulness: .5 }, primary: 'fear',
    indicators: { credentialProtection: 1, mfaSafety: 1, sensitiveDataHandling: .75 },
    records: [['Recovery-code handling', 'Recovery codes can grant account access and must not be entered into a shared spreadsheet. The requested disclosure violates the approved instructions.', 'credentialProtection'], ['Migration plan', 'The independently opened migration plan requires no collection of user recovery codes. The spreadsheet is visible to external guests.', 'mfaSafety']],
    explanation: 'The real migration does not authorize disclosure of recovery codes. Keep the codes private and report the conflicting instruction.',
  }),
  authored({ id: 'vendor-directory-export', phase: 'hard', objective: 'authorizationChecks', decision: 'phishing',
    from: 'Vendor Liaison <liaison@trusted-vendor.example>', subject: 'Employee directory needed for workshop setup',
    body: 'Please send the full employee export, including personal phone numbers and home addresses. Your manager knows us, so separate approval is unnecessary.',
    context: 'The vendor is contracted to deliver a workshop. The contract authorizes only participant names and work email addresses.',
    behavior: { familiarityImpersonation: .75, authority: .5 }, primary: 'familiarityImpersonation',
    indicators: { authorizationChecks: 1, sensitiveDataHandling: 1, requestContext: .75 },
    records: [['Approved data scope', 'The workshop agreement allows participant names and work emails only. It does not authorize personal numbers, home addresses or nonparticipant records.', 'authorizationChecks'], ['Requested export', 'The email requests the full employee dataset and explicitly asks you to skip the normal approval step.', 'sensitiveDataHandling']],
    explanation: 'An existing vendor relationship does not authorize broader data access. Withhold the export and escalate this social-engineering request through the approved process.',
  }),
  authored({ id: 'approved-aggregate-report', phase: 'hard', objective: 'authorizationChecks', decision: 'legitimate',
    from: 'Workforce Analytics <analytics@sentri.example>', subject: 'Approved monthly headcount summary',
    body: 'Please place the aggregate monthly headcount totals in the restricted analytics workspace under ticket ANA-42. Do not include employee-level records.',
    context: 'Your role maintains this aggregate report. Data owners must authorize sharing through a recorded ticket.',
    records: [['Data-owner approval', 'Ticket ANA-42, opened independently, authorizes your role to share aggregate headcount totals with the named internal analytics group.', 'authorizationChecks'], ['Report and destination scope', 'The requested report contains only team totals. The approved workspace permits access only to the authorized analytics group.', 'sensitiveDataHandling']],
    explanation: 'The data owner, requested fields and recipient permissions align with the approved ticket. Share only the authorized aggregate report in that workspace.',
  }),
  authored({ id: 'project-review-redirect', phase: 'master', objective: 'linkDestination', decision: 'phishing',
    from: 'Project Workspace <notifications@sentri.example>', subject: 'A document is ready for your review',
    body: 'The review package is available at https://workspace.sentri.example. Please use the Review package button in this message.',
    context: 'You expect a review package. The displayed link text and actual destination are available in the inspection records.',
    behavior: { curiosity: .5, familiarityImpersonation: .75 }, primary: 'familiarityImpersonation',
    indicators: { linkDestination: 1, credentialProtection: .75 },
    records: [['Actual button destination', 'The button actually leads to https://workspace.sentri.example.review-access.example/login. The destination is under review-access.example, despite the displayed company address.', 'linkDestination'], ['Workspace activity record', 'The independently opened project workspace has no review package or notification matching this message.', 'requestContext']],
    explanation: 'The actual destination differs from the displayed company address, and the expected workspace does not corroborate the message. Report it rather than signing in through the button.',
  }),
  authored({ id: 'external-training-provider', phase: 'master', objective: 'linkDestination', decision: 'legitimate',
    from: 'Learning Partner <enrollment@learning-partner.example>', subject: 'Your requested course enrollment',
    body: 'Your workshop enrollment is ready at https://learning-partner.example/enroll. You may also open it from the company learning catalog.',
    context: 'Your company uses some approved external services. An external domain alone is not a phishing verdict.',
    records: [['Approved service destination', 'The independently opened company learning catalog links to exactly https://learning-partner.example/enroll for this provider. The email button has the same destination.', 'linkDestination'], ['Enrollment record', 'Your learning catalog account shows the workshop you requested and the matching enrollment notice. No extra credentials are requested by email.', 'requestContext']],
    explanation: 'The external destination is independently corroborated by the approved catalog and matches your enrollment. This is legitimate in the scenario; use the catalog to access it.',
  }),
  authored({ id: 'director-records-request', phase: 'master', objective: 'authorizationChecks', decision: 'phishing',
    from: 'Managing Director <director@sentri.example>', subject: 'Confidential review — send the export directly',
    body: 'Send all employee compensation records to my personal mailbox today. Keep this between us and skip the data-owner approval so we can move quickly.',
    context: 'Company policy requires data-owner approval and approved destinations for employee compensation records, including requests from executives.',
    behavior: { authority: 1, urgency: .75, familiarityImpersonation: .5 }, primary: 'authority',
    indicators: { authorizationChecks: 1, sensitiveDataHandling: 1, requestContext: .75 },
    records: [['Authorization record', 'There is no data-owner approval for the export. The request explicitly asks you to bypass the required approval process.', 'authorizationChecks'], ['Destination scope', 'The requested destination is an unapproved personal mailbox and the export contains compensation records for every employee.', 'sensitiveDataHandling']],
    explanation: 'Seniority and an apparently internal sender do not override the data policy. Withhold the records and independently verify and escalate the request.',
  }),
  authored({ id: 'legal-case-subset', phase: 'master', objective: 'authorizationChecks', decision: 'legitimate',
    from: 'Legal Operations <legal@sentri.example>', subject: 'Approved documents for case LC-17',
    body: 'Please share the three approved case documents using the restricted legal workspace. Keep unrelated employee records out of the upload.',
    context: 'Your role holds documents for legal case LC-17. The data owner has a formal disclosure approval process.',
    records: [['Disclosure approval', 'The independently opened case system contains current data-owner approval for these three documents and the named legal recipients.', 'authorizationChecks'], ['Recipient and file scope', 'The restricted workspace lists only the approved recipients. The requested upload excludes unrelated employee data and matches the approved document list.', 'sensitiveDataHandling']],
    explanation: 'The independently checked approval, exact documents and workspace recipients all match. Share only that approved subset through the specified workspace.',
  }),
]
